version: '3.8'

services:
  f1-database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  f1-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=f1-database

    depends_on:
      - f1-database


  f1-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

    environment:
      - BE_SERVER=f1-backend
      - BE_PORT=8000

    depends_on:
      - f1-backend